class Aaa {
    func ccc(){}
    init(a:String){}
    let aa = 11
}
func fff(aaa!:Aaa= Aaa("sasasa")) {
    aaa.ccc()
    if (aaa.)
    match (aaa.){}
    for (i in aaa.)
}

let score4:Int64 = 90
var scoreResult4:String = match(score4){
    case 60 =>"pass"
    case 70|80 =>"good"
    case 90 |100 => "excellent"
    case failscore1 =>
        let passNeed = 60 - failsco
        "faild with ${failscore1}, and ${failscore1} nedd to pass"
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
