// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

import sub.*


@P1 func pf1(){}
@P1 @P1 enum EP1{
    |V1 | V2
}

@P2 func pf2(){
    @P1 func ggg(){}
}

@pro0.sub.P1 func fjgjgk(){}

var pa1 = pf
var pa2 = PC1().ab
var pa3 = EP1.V1
