// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

//1
package default.AA

public open class AO {
    public mut open prop i1: Int64 {
        get() { 0 }
        set(v) {}
    }
    public static mut prop i22222: Int64 {
        get() { 0 }
        set(v) {}
    }
}


