/**
*test hover hover hover 你好
*test_hover_test036
*/
open class test_hover_test036 {
    var aaa:int32 = 1
}

func run_hover_test036():unit {
    var value:test_hover_test036 = test_hover_test036()
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
