// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

/**
*test hover hover hover                     hover hover                                                                      hover                          hover                                    hover                                     hover                 hover
*test_hover_test034
*/
open class test_hover_test034 {
    var aaa:int32 = 1
}

func run_hover_test034():unit {
    var value:test_hover_test034 = test_hover_test034()
}
