// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

import testpkg.pkg_hover_001

class test_hover_test008 <: pkg_hover_001 {
    var aaa:int32 = 1
}

func run_hover_test008():unit {
    var value :test_hover_test008 = test_hover_test008()
    var a = value.add(1,2)

}
