// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

func documentHighlight_test072() :unit{
    var a1:int32 = 100
    var a1:int32 = 100
    var b:int32 = a1
    var c:int32 = a1
}
