let sum67 = (a: int32, b: int32): int32 => {a + b}
let sum67 = (a: int32, b: int32): int32 => {a + b}

func documentHighlight_test067(): unit {
    var sum2 = sum67(1, 2)
    var sum3 = sum67(1, 2)
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
