func documentHighlight_test003(): int64 {
    let tuplePIE: float32*String = (3.14, "PIE")
    let s2 : String = "Hello Char Lang"
    let s3 : String = """
                      Hello Char Lang
                      aaaaa
                      bbbbb
                      ccccc"""
    let mapSeven = {0, 1, 2, 3, 4} 
    for k in mapSeven {
        var a:int64 = k   
    }
    return 1
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
