public enum TimeUnit88
    Year | Month | Hour | Day
}

func documentHighlight_test088() {
    var value : TimeUnit88 = TimeUnit88.Day
    var value1 : TimeUnit88 = TimeUnit88.Day
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
