import testpkgerror.pkg62

func documentHighlight_test062() :unit{
    var value:pkg62 = pkg62(1)
    var value1:pkg62 = pkg62(1)
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
