func documentHighlight_test064() {
    func test_iner() :int32{
        return 1
    }
    func test_iner1() :int32{
        return 1
    }
    var a:int32 = test_iner()
    var a1:int32 = test_iner1()
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
