// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

public enum TimeUnit85 {
    Year | Month | Hour | Day | Day
}

func documentHighlight_test085() {
    var value : TimeUnit85 = TimeUnit85.Day
    var value1 : TimeUnit85 = TimeUnit85.Day
}
