// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

internal package reExport.export.funcs

public class A {

}

public func foo1() {

}

public func foo2() {

}

public func foo3() {

}

public func foo4() {

}

public func foo5() {

}

public func fooo(a: Int32) {

}