// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package B
public var varC = 1
public let letC = 1
public class classC{ func classTest( )  {

}}
public enum enumC{|d|a|y}
public struct structC{}
public interface interfaceC{}
