// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package default.pkgB
public import default.pkgD.ccc as ff

public struct pkgBstruct{
    let ddd = 22
    init(a:Int64)  {

    }
    pkgBstruct(a:Int64,b:Int64){}
    let a  = 1
    let ccccccccc = 2
    static func cccc( )  {

    }
}

public let pkgBdddd = 2222

class pkgBCLASS{
    let ddd = 22
    init(a:Int64)  {

    }
    pkgBCLASS(a:Int64,b:Int64){}
    let a  = 1
    let ccccccccc = 2
    static func cccc( )  {

    }
}
func pkgBAA(A:Int64 )  {
	 1
}
let c = pkgB.p
