open class RE {
    var width:Int64 = 1
    var height:Int64 = 2
    init() {}
    init(width:Int64,height:Int64){
        this.width = width
        this.height = height
    }
}
class CC <: RE {
    var a:Int64
    init(a:Int64) {
        this.a = super.
    }
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
