import aoo.*
import boo.*
from pro1 import xoo.*
from pro1 import yoo.*
from pro2 import zoo.*

main(): Int64 {
    let a = aoo.one
    let b = boo.two
    let e = xoo.x
    let f = yoo.
    let g = zoo.z
    let res = a + b
    let res2 = e + f + g
    if (res != 3 || res2 != 101) {
        return 1
    }
    x
    return 0
}

// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
