package C 

import BBB.*

@B1 func fb1(x:Int64){
    var aa = x
    func ff2(){
        fb1(9)
    }
} 

@B1(C1().ab)
@B1(var tt = 1)
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
