// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package pkgB.pkg2

public import pkgB.pkg1.AAA
import pkgB.pkg1.foooo2

public let aa = AAA()


public func fooo2(a: AAA) {
    // foo1()
    foooo2()
    let x = 0
}

