import A.* as A1.*
import A.*
import A.* as A2.* , B.* as B2.*
import A.* as A3.* , B.*
import A.* , B.*
import A.* , B.* as B3.*
import A.* , B.* as B3.b2134
// import A.varC as A4.d
import A.varC as aVarC
import B.varC as bVarC
func main() {
    return 0
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
