package default
import std.unittest.*
import std.unittest.testmacro.*
import default.AA.*
import default.AA.BB.*

@Test class BCA{
    func gds(){}
}
@Test func ffss(){}

@MA1
func t1() {}

@MA1
func t2() {}

@MB1
func t3() {}

@MB1
func t4() {}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
