// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

features {user.lib.arch.big, user.lib.arch.big2, user.lib.arch.big3}
package lib

public specific func message(): Unit {
    println("Some example message")
}

public specific func message1(): Unit {
    println("Some example message")
}
