// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package directory2

public var dir1_a1 = pkg1_c1()

func test1() {
    dir1_a1.test1()
}

public class dir1_c1 {
    public var a1 = dir1_a1.test1()
}

