struct Rectangle111 {
    let width1: Int32 = 10
    let length1: Int32 = 20
    var test_var: Int32 = 30
    let perimeter1: () ->Int32 = { =>2 * (width1 + length1) }
    init (width1: Int32, length1: Int32) {
    this.width1 = width1
    this.length1 = length1
}
init (side: Int32) {
    this.width1 = side
    this.length1 = side
}
func area1(): Int32 = width1 * length1

func area2(): Int32 = {
    this.test_var = 10 // Record成员函数函数体内只能访问let定义的成员变量检查 ??
    test_var = 10
    var a = this.width1
    // 要用this吗？
    return 1
}


struct Rectangle321 {
    public var length : Int32           // 未初始化的非静态成员变量定义
    private var width : Int32 = 0       // 初始化的非静态成员变量定义
    var diagonalLength: Int32 = 0
    static var name : String = "Rec"    // 静态成员变量

    init(length: Int32) {           // OK: 成员变量 `length` 完成初始化
        this.length = length
    }
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
