// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

/**
 * Created on 2025/2/26
 */
package ohos_app_cangjie_entry.test12

protected  interface Iter12 {
    func testcase12(): Unit {}
}
extend Test12 <: Iter12 {
    public func testcase12(): Unit {}
}
