import default.com
import default.com.b

let cc1 = com.enumTest.a
let cc2 = b.t
let cc3 = com.s
let cc4 : com.s =
let cc5 : b.e =

// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
