// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

import default.A.*
struct structTest{
    let r = 0
}
class classTest{
	let c = 1
}
let aaa:A = 1
let ccc = structTest
let ddd = enumTest.Dear
let eee = $
