// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

func ddd() {
    let a: Option<Int64> = Some(100)
    if (let Some(vvvvv) = a) {
        var t1 = vvv
    }
}

class CC{
    var a = 11
    public mut prop b:Int64 {
        get(){return 0}
        set(valuexxx){
            a = valuexx
        }
    }
}

