// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

/**
 * Created by code_project on 2021/9/11
 */
package default.pkgD
import CCC.*

let pkgDc= 3333
let pkgDd = 2
struct pkgDTest { init(a:Int32){}}
public class pkgDTestClass {  init(a:Int32){}}
let a = pk

