import default.package1
import std.math.*

public var a = 1

public class dir1_c {
    public var a1 = package1.pkg1_c1()
    public func test1() {}
}

func test1() {
    var a1 = package1.
    var a2 = pac
    var a3 = package1.pkg1_c1()
    var s4 = a3.
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
