public open interface I1{
    open func ff1():Unit{}
}
public class CC{}

func name() {
    name11.public()
}

class name11 {
    static public func public(){}
}

func name1() {
    name11.public()
}

public class aaa<:Exception{}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
