// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package cangjieextend.direct2

// When a direct extension is in the same `package` as the definition of the extended type, whether the extension is exported is determined by the minimum access level of the extended type and the type used in the generic constraint, if any.
