let now1111 = DateTime.now()
var result3 = """
 时间:${now1111.year}年
 ${now1111.month}月"""
func chinese(str: String,/*中文*/ variable!: Int64) {
    
}

func test() {
   """
 时间:${now1111.year}年
 ${now1111.month}月""" ; chinese(##"中文"##, variable: 1);
        chinese("""
                中文""", vari)
}

// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
