// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package alias.pkgUA

import alias.pkgA.*

func fu1() {
    // completion zz
    zz

}

func fu2() {

    let a123 = CA123()
    // completion 123.
    a123.

}