class ABCDEFG{
    func DDD(){}
    let aaa =1
}

let dd = "a s ${ABCDEFG().}s ddDD "
let dds = """
ss SD
s_MofuncC
s sss sa  AAdsads ${ ABCDEFG(). }
"""
main(){

}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
