// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package default.test2

public func fb(){}

public class SA{
    var a:Int64 = 1
    SA(z:Int64){
        print("11");
    }
}

var mn1 = test2.fb()

