// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package default.A 
import default.C.*

@When[feature1 == "cat"]
func test1() {

}

@When[feature2 == "cat"]
func test2() {
    
}

@When[feature1 == "lion"]
func test3() {

}

@When[feature2 == "cat"]
func test4() {
    
}


func use() {
    test1()
    test2()
    test3()
    test4()
    test5()
}
