public struct S1 {
    public S1(x: Int64, var width!: Int64 = 8) {}
    public static let mm1 = 8
    public var nn = 7
}

var width: Int64 = 8

public func fun1(x: Int64, width!: Int64 = 8) {}

// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
