package pro0.log

public var ac = 1
public class CC {
    public init(a: Int64) {}
    public var ccd = 1
    public static var caa = 0
    public func ff() {}
}

public func name() {
    var b1 = CC(6)
    b1.ccd
    CC.caa
}

// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
