// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package pkgB.pkg1

public func foo1() {
    let x: Int32 = 0
    x 
}

public func foo3(){}

public class AA {
    private func ff() {
         
    }

    public func qqq() {

    }

    internal func ddd() {

    }

    protected func mmm() {

    }
}

public type AAA = AA

public func foooo2() { 

}

func fff() {
    
}

