// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.



struct Rectangle1 {
    // 成员变量
    let width: Int32 = 10
    let length: Int32 = 20

    // 构造函数
    init (width: Int32, length: Int32) {
        this.width = width
        this.length = length
    }

    // 成员函数
    func area(): Int32 { 
        return width * length 
    }
}

interface ToString {
    func toString() : String1
}

struct String1 <: ToString { // Implement `ToString` interface directly.
    func toString() : String1 {
        return this
    }
}

interface Hashable {
    func hashCode() : UInt64 
}

extend String1 <: Hashable { // Implement `Hashable` interface using extend.
    func hashCode() : UInt64 {
        return 0 // Not real implementation.
    }
}

// 互递归
struct R4 { // ok
    let other: E1
}
enum E1 { // ok
    A(R4)
}



struct Rectangle2 {
    private var length : Int32 = 0
    private var width : Int32 = 0
    private var perimeter: Int32 = 0
    init(length: Int32, width: Int32) {
        this.length = length
        this.width = width
    }
    func getPerimeter() {
        return this.perimeter // Ok: 函数可通过 `this.memberName` 的方式访问名为 `memberName` 的实例成员变量；
    }
}


struct Rectangle3 {
    private var length : Int32 = 0
    private var width : Int32 = 0
    private init() {}
    public init(squareLength: Int32) {

        this.length = squareLength
        this.width = squareLength
    }
    init(length: Int32, width: Int32) {
        this.length = length
        this.width = width
    }
}

func generateRectangele() {
    var rectangle2 = Rectangle3(5)    // OK: public修饰的init构造函数可在struct外访问
    var rectangle1 = Rectangle3(3, 4) // OK: 缺省时为public，无`public` 或 `private` 修饰的init构造函数可在struct外访问
    var rectangle3 = Rectangle3()     // ERROR: private修饰的init构造函数不可在struct外访问
}
