from std import collection.*
class Test {
    public var m = 1
    private var p = 2
    public func df() {}
    public init() {}
}


func foo() {
    let a = Test()
    let b = Test()
    let c = Test()
    let arr: Array<Test> = [a, b, c]
    for (i in arr where i.) {

    }
}


// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
