open class Base20 {
    protected var one:int32 = 1
    private var a: int32 = 0
    init(a: int32) {
        this.a = a
    }

    public func add(a: int32, b: int32):int32 {
        return a + b + this.one
    }

    open func add2(a: int32, b: int32):int32 {
        return a + b
    }

    func test():int32 {
        return this.add(1,2)
        
    }
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
