// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

func semanticHighlight_test053(): unit {
    var a1: int8 = 10
    var a2: int16 = 10
    var a3: int32 = 10
    var a4: int64 = 10
    var a5: uint8 = 10
    var a6: uint16 = 10
    var a7: uint32 = 10
    var a8: uint64 = 10
    var a9: floa8 = 10.0 // 不存在，error
    var a10: float32 = 10.0
    var a11: float32 = 10.0
    var a12: float64 = 10.0
    var a13: bool = true
    var a14: unit = ()
    var a15: char = 'a'
}

