// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

func semanticHighlight_test007(): unit {
    var test1: int8 = 2
    var test2: int16 = 2
    var test3: int32 = 2
    var test4: int64 = 2
    var test5: uint8 = 2
    var test6: uint16 = 2
    var test7: uint32 = 2
    var test8: float16 = 2
    var test9: float32 = 2
    var test10: float64 = 3.14
    var test11: float64 = 2.4e-1
    var test12: float64 = .8
    var test13: float64 = .123e2
    var test14: float64 = 0x1.1p0
    var test15: float64 = 0x1p2
    var test16: float64 = 0x.2p4
    var test17: float64 = 120.189
    var level: char = 'A'
    let bool1: bool = true 
    let bool2: bool = false
}
