// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

func semanticHighlight_test028_1(a:int64): int64 {
    return a
}

func semanticHighlight_test028_1(a:int64): int64 {
    return a
}

func semanticHighlight_test028(): int64 {
    return semanticHighlight_test028_1(1)
}
