// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

interface I12 {
    let a: int32 = 1
    func add(a: int32, b: int32):int32
    func getNum():int32 {
        return 1
    }
    
    static func getSum():int32 {
        return 1
    }
}

class Base12 <: I12 {
	var a:int32 = 3
    init(a: int32) {
        this.a = a
    }

    func add(a: int32, b: int32):int32 {
        return a + b + I12.getSum()
    }

    func add(a: int32):int32 {
        return a + getNum()
    }

    func add():int32 {
        return I12.a
    }
}

func semanticHighlight_test012():unit {
    var value:Base12 = Base12(1)
    var a = value.getNum()
    var b = value.add(1,2)
}
