//1234
internal open class Point {
    var x1: Int8 = 0
    var x2: Int16 = 0
    var x3: Int32 = 0
    var x4: Int64 = 0
    var x5: UInt8 = 0
    var x6: UInt16 = 0
    var x7: UInt32 = 0
    var x8: UInt64 = 0
    var x9: Float16 = 0
    var x10: Float32 = 0
    var x11: Float64 = 0
    var x12: Rune = ' '
    var x13: Bool =true
    var x14: Unit = ()
}

// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
