// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

func e1() {
    let list1 = [4,5,6]
    let list = [1,2,3,*list1,3,2,1]
    let  a:Int32 = 1
    a = 10
    var b:Int32 = 2
    let e:Int8 = 1233211
    3<4<5
    let x1:UInt8 =30
    let y1 = x1>>11
    let r1 = x1 >>-2
    true ^^2.0
    let c=a>b?a:b
    let d:Float32 = a>b?a:b
    if(a =5) {}
}

