import default.pkg.SS as ZZ
func func1(){ 
    
    var x1 = SS<Int64>(6) 
    var x2 = SS<Bool>.num 
    var x3 = NN<Int64>.num 
    var x4 = ZZ
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
