package default.pkg

@When[cc44 == "c5"]
func testC4() {

}

@When[cc55 == "c5" && cc22 == "c5"]
func testC6() {

}

@When[cc55 == "c3" || cc33 == "c3"]
func testC6() {

}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
