/**
 * Created on 2024/11/22
 */
package ohos_app_cangjie_entry
import test_no_src_dir_config.test.testNoSrcDirConfig

func testGotoNoSrcConfig() {
    testNoSrcDirConfig()
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
