/**
 * Created on 2024/11/21
 */
package ohos_app_cangjie_entry
import test_custom_src.custom_src_func
import ohos_app_cangjie_entry.src.testPkg
import test_custom_src.testPkg.testCustomSrcPkg

func name() {
	testPkg()
    custom_src_func()
    testCustomSrcPkg()
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
