package test2024122448454

main(): Int64 {
    println("hello world")
    return 0
}

class AA {
    var xxx = 10
}

func test1() {
    var _aa11 = AA()
    var s = """
    xxxxx xxxxxxxxxxxx
    xxx${_aa11
    .xxx}""";
    var s1 = "xxx${_aa11.xxx}";
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
