// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

func intnative(){
    var a: Int8 = 128
    var b: Int8 = 127

    var c: UInt8 = 256
    var d: UInt8 = 255
    var e: UInt8 = 0
    var f: UInt8 = -1

    var g: IntNative = 1234
    var h: UIntNative = 1234567
}
