// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package default.pkgAa
public import default.pkgB

public let pkgAaa = 1
public let pkgAbb = 1
let pkgAcc = 1
let pkgAdd = 12
let pkgAff = pkgB.f
let d = 1
