// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package my_module

public type Byte_ = UInt8

/*FIXME: Non-constant global variable details need to be verified and rewritten by user.*/
/* Byte byte1 = 'a' */

/*FIXME: Non-constant global variable details need to be verified and rewritten by user.*/
/* Byte byte1 = 'a' , byte2 = 'b' */

public type byte = UInt8
