// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package my_module

public const ch: UInt8 = 97
public const a: Int32 = 0
public const b: UInt32 = 0
public const c: Int16 = 0
public const d: UInt16 = 0
public const f: Int64 = 0
public const g: UInt64 = 0
public const x: Float32 = 1.0
public const e: Float64 = 1.0
public const MAX: Int32 = 10
