// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package cangjieextend.interface1

// When the interface extension is in the same `package` as the extended type, the extension is exported together with the extended type and is not affected by the access level of the interface type. The members of the extension can be accessed without importing the interface type.
