// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package default.2022031808222

//代码1：
class a/A{}
class 23A{}
open class `A`{}
class D<1E> {}

class CC{
    var _aa=9
}
//代码2：
var I1 = 3
enum Iq1 {}

//代码3：
enum Time2{
    Day(Int64) | _Hour

}
