// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

class CC1 {
    CC1(){}
    static func test1() {}
    static prop aa: Int64 {
        get() {
            0
        }
    }
}

extend CC1{
    func test2() {
        
    }
}

func tt1() {
    var cc = CC1()
    default.
}

func tt2() {
    var cc = CC1()
    cc.
}

