// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

class AB {
}

class AC {
    AC() {}
}

class AD {
    AD(a:Int64) {
        super()
    }
    init() {
        let a = 1
    }
}

class AA {
    AA(let a:Int64) {
        let b = a;
        let c = 1
    }
}
