func hover_test040() :unit{
     let mapOne: Map<int32, String> = #{1: "Aa", 2: "Bb", 3: "Cc", 1: "fir"}
     mapOne.size()
 }
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
