// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package USE

import CCC.*
@MM2[class MI{var xy1 =1}]
class MI2{
    func fm1(){}
}

@BB3[public](func fbb2(){
    var r1 =abc2
})


