// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package default.b

import default.a.*
public interface blackPeople <: People{

}
public open class student <: xzf & People {
    public static var name: String = "aaaa";
    public static func studentage() {
        xzfage()
    }
}
 public struct IT <:love{
     public static var name: String = "aaaa";
 }


