// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package default.pkg_alias03
public import pkg_alias01.var02 as a2
public import pkg_alias01.func02 as f2

public var xxx = 666

public func func02(a:Int64) {
    return 3
}
