/**
 * Created on 2025/6/4
 */
package ohos_app_cangjie_entry.A.B

class food {}

@When[feature == "lion"]
func fee() {
    food()
    println("feature lion")
}

@When[feature == "tiger"]
func fee() {
    food()
    println("feature tiger")
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
