let str1 = "fdkgsldfg,dfgsdfg/sfgsdfkgsdrg""
var str2 : String = str1
class func001{
	 func func001() {
        str
    }
}
var xxx1: Int8 = 1
var xxxx2 : Int16 = 1
var xxxxx3 : Int8 = 123
var xxx333 : Int16 = 223
var xxxx111 : Int32 = 2323
var yy11 : Int64=11122
let i : String = "aa"
func func002() {
	 yy11
	 if (i == str1) {
	    xxx1
    }
}

class foo1 {
    var xxx1 = "3333"
    func fun003() {
	    xxx1
    }
}



// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
