// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package primaryTyExtend

main(): Int64 {
    var a: Int8 = 8
    a
    100
    100.10
    var b: Rune = "a"
    b
    var c: Bool = true
    c
    false
    return 0
}