let ad1:(p1:Int64,p11:Int64)->Int64={a:Int64,b:Int64=>a+b}
let ad2:(p1:Int64,p2:Int64)->Int64 ={n,_ => n}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
