let a = pkgA.public_pkgA_enum.enumA.public_pkgA_enum_func(,public_pkgA_enum_funcb2:, public_pkgA_enum_funcs2:)
let b = cur_class(1).cur_class_func(1,cur_class_funcb1:,)
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
