package FollowLambdaCompletion.var_test.auto_import_completion.pkg2
import FollowLambdaCompletion.var_test.auto_import_completion.pkg1.auto_import_var1

func auto_import_test() {
    var a = auto_import_var1
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
