// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package doc.USE

import doc.CCC.*

@M3 func foob():Int64{
    foob()
}

//@M3 var ak1 = 0

func test38(){
    var b = fooa(12.3)
    var c = fooa
    var d = c(1.2)
}
