package doc.USE

@M2 class MC1{   
    init(){}
    init(x:Int64,y:Float16){
    }

    var aabb = 9
}

var cm1 = CM().aabb
var cm2 = CM().bbcc
var cm3 = CM(1,3.6).hh1()

var cm5 = CM().bbcc
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.
