// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package my_module

import ohos.ark_interop.*
import ohos.ark_interop_helper.*
import ohos.base.*
import tpc.AbilityKit.common
/***********IMPORT***********/
/*FIXME: Import details need to be verified and rewritten by user.*/
/*import {p29} from "./superInterface"*/


/***********OBJECT***********/

/*interface A {
    p: number;
    }*/

public open class A {
    
    protected A(private var p: Float64) { }
    
    
    public open func toJSValue(context: JSContext): JSValue {
        let obj = context.object()
        obj["p"] = p.toJSValue(context)
        obj.toJSValue()
    }
    
    public static func fromJSValue(context: JSContext, input: JSValue): A {
        let obj = input.asObject()
        A(
        Float64.fromJSValue(context, obj["p"])
        )
    }
    
}

/*interface B {
    p1: number;
    }*/

public open class B <: A {
    
    protected B(p: Float64,
    private var p1: Float64) { super(p) }
    
    
    public open func toJSValue(context: JSContext): JSValue {
        let obj = context.object()
        obj["p"] = p.toJSValue(context)
        obj["p1"] = p1.toJSValue(context)
        obj.toJSValue()
    }
    
    public static func fromJSValue(context: JSContext, input: JSValue): B {
        let obj = input.asObject()
        B(
        Float64.fromJSValue(context, obj["p"]),
        Float64.fromJSValue(context, obj["p1"])
        )
    }
    
}

/*interface ExportKeyword BuglyLogAdapter {
    }*/

public open class BuglyLogAdapter <: p29 {
    
    protected BuglyLogAdapter(public var arkts_object: JSObject) { super(arkts_object) }
    
    
    
    public open func toJSValue(context: JSContext): JSValue {
        arkts_object.toJSValue()
    }
    
    public open  static func fromJSValue(context: JSContext, input: JSValue): BuglyLogAdapter {
        BuglyLogAdapter(input.asObject())
    }
}

/*interface C {
    f(): void
    }*/

public open class C {
    
    protected C(public var arkts_object: JSObject) { }
    
    
    /**
	 * @brief f(): void
	 */
    public func f(): Unit {
        jsObjApiCall < Unit >( arkts_object, "f", emptyArg)
    }
    
    public open func toJSValue(context: JSContext): JSValue {
        arkts_object.toJSValue()
    }
    
    public open  static func fromJSValue(context: JSContext, input: JSValue): C {
        C(input.asObject())
    }
}

/*interface D {
    }*/

public open class D <: C {
    
    protected D(public var arkts_object: JSObject) { super(arkts_object) }
    
    
    
    public open func toJSValue(context: JSContext): JSValue {
        arkts_object.toJSValue()
    }
    
    public open  static func fromJSValue(context: JSContext, input: JSValue): D {
        D(input.asObject())
    }
}

/*interface E {
    }*/

public open class E <: A {
    
    protected E(p: Float64) { super(p) }
    
    
    public open func toJSValue(context: JSContext): JSValue {
        let obj = context.object()
        obj["p"] = p.toJSValue(context)
        obj.toJSValue()
    }
    
    public static func fromJSValue(context: JSContext, input: JSValue): E {
        let obj = input.asObject()
        E(
        Float64.fromJSValue(context, obj["p"])
        )
    }
    
}

/*interface F {
    g(): void
    }*/

public open class F <: C {
    
    protected F(public var arkts_object: JSObject) { super(arkts_object) }
    
    
    /**
	 * @brief g(): void
	 */
    public func g(): Unit {
        jsObjApiCall < Unit >( arkts_object, "g", emptyArg)
    }
    
    public open func toJSValue(context: JSContext): JSValue {
        arkts_object.toJSValue()
    }
    
    public open  static func fromJSValue(context: JSContext, input: JSValue): F {
        F(input.asObject())
    }
}

/*interface ExportKeyword DeclareKeyword SuperInterface {
    p: number;
    }*/

public open class SuperInterface {
    
    protected SuperInterface(private var p: Float64) { }
    
    
    public open func toJSValue(context: JSContext): JSValue {
        let obj = context.object()
        obj["p"] = p.toJSValue(context)
        obj.toJSValue()
    }
    
    public static func fromJSValue(context: JSContext, input: JSValue): SuperInterface {
        let obj = input.asObject()
        SuperInterface(
        Float64.fromJSValue(context, obj["p"])
        )
    }
    
}

/*class ExportKeyword DeclareKeyword SubClass {
    p: number;
    }*/

public class SubClass <: SuperClass {
    
    protected SubClass(public var arkts_object: JSObject) { super(arkts_object) }
    
    
    public mut prop p: Float64 {
        get() {
            checkThreadAndCall < Float64 >(getMainContext()) {
                ctx: JSContext => Float64.fromJSValue(ctx, arkts_object["p"])
            }
        }
        set(v) {
            checkThreadAndCall < Unit >(getMainContext()) {
                ctx: JSContext => arkts_object["p"] = v.toJSValue(ctx)
            }
        }
        
    }
    
    
    public func toJSValue(context: JSContext): JSValue {
        arkts_object.toJSValue()
    }
    
    public  static func fromJSValue(context: JSContext, input: JSValue): SubClass {
        SubClass(input.asObject())
    }
}

/*class ExportKeyword DeclareKeyword SubClass1 {
    p: number;
    }*/

public class SubClass1 <: SuperClass1 {
    
    protected SubClass1(public var arkts_object: JSObject) { super(arkts_object) }
    
    
    public mut prop p: Float64 {
        get() {
            checkThreadAndCall < Float64 >(getMainContext()) {
                ctx: JSContext => Float64.fromJSValue(ctx, arkts_object["p"])
            }
        }
        set(v) {
            checkThreadAndCall < Unit >(getMainContext()) {
                ctx: JSContext => arkts_object["p"] = v.toJSValue(ctx)
            }
        }
        
    }
    
    
    public func toJSValue(context: JSContext): JSValue {
        arkts_object.toJSValue()
    }
    
    public  static func fromJSValue(context: JSContext, input: JSValue): SubClass1 {
        SubClass1(input.asObject())
    }
}

/*class ExportKeyword DeclareKeyword SubInterface {
    p: number;
    p1: number;
    }*/

public class SubInterface <: SuperInterface {
    
    protected SubInterface(public var arkts_object: JSObject) {
        super(Float64.fromJSValue(getMainContext(), arkts_object["p"])) }
    
    
    public mut prop p: Float64 {
        get() {
            checkThreadAndCall < Float64 >(getMainContext()) {
                ctx: JSContext => Float64.fromJSValue(ctx, arkts_object["p"])
            }
        }
        set(v) {
            checkThreadAndCall < Unit >(getMainContext()) {
                ctx: JSContext => arkts_object["p"] = v.toJSValue(ctx)
            }
        }
        
    }
    
    public mut prop p1: Float64 {
        get() {
            checkThreadAndCall < Float64 >(getMainContext()) {
                ctx: JSContext => Float64.fromJSValue(ctx, arkts_object["p1"])
            }
        }
        set(v) {
            checkThreadAndCall < Unit >(getMainContext()) {
                ctx: JSContext => arkts_object["p1"] = v.toJSValue(ctx)
            }
        }
        
    }
    
    
    public func toJSValue(context: JSContext): JSValue {
        arkts_object.toJSValue()
    }
    
    public  static func fromJSValue(context: JSContext, input: JSValue): SubInterface {
        SubInterface(input.asObject())
    }
}

/*class ExportKeyword DeclareKeyword FirstContextualKeyword SuperClass {
    p: number;
    }*/

public open class SuperClass {
    
    protected SuperClass(public var arkts_object: JSObject) { }
    
    
    public mut prop p: Float64 {
        get() {
            checkThreadAndCall < Float64 >(getMainContext()) {
                ctx: JSContext => Float64.fromJSValue(ctx, arkts_object["p"])
            }
        }
        set(v) {
            checkThreadAndCall < Unit >(getMainContext()) {
                ctx: JSContext => arkts_object["p"] = v.toJSValue(ctx)
            }
        }
        
    }
    
    
    public open func toJSValue(context: JSContext): JSValue {
        arkts_object.toJSValue()
    }
    
    public open  static func fromJSValue(context: JSContext, input: JSValue): SuperClass {
        SuperClass(input.asObject())
    }
}

/*class ExportKeyword DeclareKeyword SuperClass1 {
    p: number;
    }*/

public open class SuperClass1 {
    
    protected SuperClass1(public var arkts_object: JSObject) { }
    
    
    public mut prop p: Float64 {
        get() {
            checkThreadAndCall < Float64 >(getMainContext()) {
                ctx: JSContext => Float64.fromJSValue(ctx, arkts_object["p"])
            }
        }
        set(v) {
            checkThreadAndCall < Unit >(getMainContext()) {
                ctx: JSContext => arkts_object["p"] = v.toJSValue(ctx)
            }
        }
        
    }
    
    
    public open func toJSValue(context: JSContext): JSValue {
        arkts_object.toJSValue()
    }
    
    public open  static func fromJSValue(context: JSContext, input: JSValue): SuperClass1 {
        SuperClass1(input.asObject())
    }
}

