// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package my_module

import ohos.ark_interop.*
import ohos.ark_interop_helper.*
import ohos.base.*

public enum AutoGenType0Inissue_issue8_generic {
    | NUMBER(Float64)
    | STRING(String)
    
    public func toJSValue(context: JSContext): JSValue {
        match(this) {
            case NUMBER(x) => context.number(x).toJSValue()
            case STRING(x) => context.string(x).toJSValue()
        }
    }
    public static func fromJSValue(context: JSContext, input: JSValue): AutoGenType0Inissue_issue8_generic {
        
        if(input.isNumber()) {
            return NUMBER(Float64.fromJSValue(context, input))
        }  
        if(input.isString()) {
            return STRING(String.fromJSValue(context, input))
        }
        throw Exception("unsupport type!")
    }
}


/*class ExportKeyword DeclareKeyword C {
    f(p:T): number | String
    }*/

public class C {
    
    protected C(var arkts_object: JSObject) { }
    
    
    /**
	 * @brief f(p:T): number | String
	 */
    public func f < T >(p: T): AutoGenType0Inissue_issue8_generic where T <: JSInteropType<T> {
        jsObjApiCall < AutoGenType0Inissue_issue8_generic >( arkts_object, "f", { ctx =>[p.toJSValue(ctx)] }) { ctx, info => AutoGenType0Inissue_issue8_generic.fromJSValue(ctx, info) }
    }
    
    func toJSValue(context: JSContext): JSValue {
        arkts_object.toJSValue()
    }
    
    static func fromJSValue(context: JSContext, input: JSValue): C {
        C(input.asObject())
    }
}

