// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package my_module

import ohos.ark_interop.*
import ohos.ark_interop_helper.*
import ohos.base.*


public type TB230< V, W > = (V) -> W/* FIXME: `<V, W extends "abc" | "def">(arg: V) => W` */


public type TB300 = JSValue/* FIXME: `Promise<number>` */


public type TB310 = Array<JSValue/* FIXME: `Promise<boolean>` */>


